//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminGUI.ReservationService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Station", Namespace="http://schemas.datacontract.org/2004/07/DomainModel.Models")]
    [System.SerializableAttribute()]
    public partial class Station : AdminGUI.ReservationService.Entity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsArchivalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsArchival {
            get {
                return this.IsArchivalField;
            }
            set {
                if ((this.IsArchivalField.Equals(value) != true)) {
                    this.IsArchivalField = value;
                    this.RaisePropertyChanged("IsArchival");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Entity", Namespace="http://schemas.datacontract.org/2004/07/DomainModel")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AdminGUI.ReservationService.Connection))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AdminGUI.ReservationService.ConnectionDefinition))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AdminGUI.ReservationService.Train))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AdminGUI.ReservationService.User))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AdminGUI.ReservationService.Station))]
    public partial class Entity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] VersionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Version {
            get {
                return this.VersionField;
            }
            set {
                if ((object.ReferenceEquals(this.VersionField, value) != true)) {
                    this.VersionField = value;
                    this.RaisePropertyChanged("Version");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Connection", Namespace="http://schemas.datacontract.org/2004/07/DomainModel.Models")]
    [System.SerializableAttribute()]
    public partial class Connection : AdminGUI.ReservationService.Entity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ArrivalTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AvailableSeatNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AdminGUI.ReservationService.ConnectionDefinition ConnectionDefinitionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DepartureTimeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ArrivalTime {
            get {
                return this.ArrivalTimeField;
            }
            set {
                if ((this.ArrivalTimeField.Equals(value) != true)) {
                    this.ArrivalTimeField = value;
                    this.RaisePropertyChanged("ArrivalTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AvailableSeatNo {
            get {
                return this.AvailableSeatNoField;
            }
            set {
                if ((this.AvailableSeatNoField.Equals(value) != true)) {
                    this.AvailableSeatNoField = value;
                    this.RaisePropertyChanged("AvailableSeatNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AdminGUI.ReservationService.ConnectionDefinition ConnectionDefinition {
            get {
                return this.ConnectionDefinitionField;
            }
            set {
                if ((object.ReferenceEquals(this.ConnectionDefinitionField, value) != true)) {
                    this.ConnectionDefinitionField = value;
                    this.RaisePropertyChanged("ConnectionDefinition");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DepartureTime {
            get {
                return this.DepartureTimeField;
            }
            set {
                if ((this.DepartureTimeField.Equals(value) != true)) {
                    this.DepartureTimeField = value;
                    this.RaisePropertyChanged("DepartureTime");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConnectionDefinition", Namespace="http://schemas.datacontract.org/2004/07/DomainModel.Models")]
    [System.SerializableAttribute()]
    public partial class ConnectionDefinition : AdminGUI.ReservationService.Entity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AdminGUI.ReservationService.Station ArrivalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AdminGUI.ReservationService.Station DepartureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsArchivalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AdminGUI.ReservationService.Train TrainField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.TimeSpan TravelTimeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AdminGUI.ReservationService.Station Arrival {
            get {
                return this.ArrivalField;
            }
            set {
                if ((object.ReferenceEquals(this.ArrivalField, value) != true)) {
                    this.ArrivalField = value;
                    this.RaisePropertyChanged("Arrival");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AdminGUI.ReservationService.Station Departure {
            get {
                return this.DepartureField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartureField, value) != true)) {
                    this.DepartureField = value;
                    this.RaisePropertyChanged("Departure");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsArchival {
            get {
                return this.IsArchivalField;
            }
            set {
                if ((this.IsArchivalField.Equals(value) != true)) {
                    this.IsArchivalField = value;
                    this.RaisePropertyChanged("IsArchival");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AdminGUI.ReservationService.Train Train {
            get {
                return this.TrainField;
            }
            set {
                if ((object.ReferenceEquals(this.TrainField, value) != true)) {
                    this.TrainField = value;
                    this.RaisePropertyChanged("Train");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan TravelTime {
            get {
                return this.TravelTimeField;
            }
            set {
                if ((this.TravelTimeField.Equals(value) != true)) {
                    this.TravelTimeField = value;
                    this.RaisePropertyChanged("TravelTime");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Train", Namespace="http://schemas.datacontract.org/2004/07/DomainModel.Models")]
    [System.SerializableAttribute()]
    public partial class Train : AdminGUI.ReservationService.Entity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsArchivalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SeatNoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsArchival {
            get {
                return this.IsArchivalField;
            }
            set {
                if ((this.IsArchivalField.Equals(value) != true)) {
                    this.IsArchivalField = value;
                    this.RaisePropertyChanged("IsArchival");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SeatNo {
            get {
                return this.SeatNoField;
            }
            set {
                if ((this.SeatNoField.Equals(value) != true)) {
                    this.SeatNoField = value;
                    this.RaisePropertyChanged("SeatNo");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/DomainModel.Models")]
    [System.SerializableAttribute()]
    public partial class User : AdminGUI.ReservationService.Entity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PassWordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PassWord {
            get {
                return this.PassWordField;
            }
            set {
                if ((object.ReferenceEquals(this.PassWordField, value) != true)) {
                    this.PassWordField = value;
                    this.RaisePropertyChanged("PassWord");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNo {
            get {
                return this.PhoneNoField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNoField, value) != true)) {
                    this.PhoneNoField = value;
                    this.RaisePropertyChanged("PhoneNo");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ReservationService.IReservationManagment")]
    public interface IReservationManagment {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservationManagment/DepartureStations", ReplyAction="http://tempuri.org/IReservationManagment/DepartureStationsResponse")]
        AdminGUI.ReservationService.Station[] DepartureStations();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservationManagment/DepartureStations", ReplyAction="http://tempuri.org/IReservationManagment/DepartureStationsResponse")]
        System.Threading.Tasks.Task<AdminGUI.ReservationService.Station[]> DepartureStationsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservationManagment/ArrivalStations", ReplyAction="http://tempuri.org/IReservationManagment/ArrivalStationsResponse")]
        AdminGUI.ReservationService.Station[] ArrivalStations();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservationManagment/ArrivalStations", ReplyAction="http://tempuri.org/IReservationManagment/ArrivalStationsResponse")]
        System.Threading.Tasks.Task<AdminGUI.ReservationService.Station[]> ArrivalStationsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservationManagment/FindConnection", ReplyAction="http://tempuri.org/IReservationManagment/FindConnectionResponse")]
        AdminGUI.ReservationService.Connection[] FindConnection(AdminGUI.ReservationService.Station departure, AdminGUI.ReservationService.Station arrival, System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservationManagment/FindConnection", ReplyAction="http://tempuri.org/IReservationManagment/FindConnectionResponse")]
        System.Threading.Tasks.Task<AdminGUI.ReservationService.Connection[]> FindConnectionAsync(AdminGUI.ReservationService.Station departure, AdminGUI.ReservationService.Station arrival, System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservationManagment/FindEmail", ReplyAction="http://tempuri.org/IReservationManagment/FindEmailResponse")]
        bool FindEmail(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservationManagment/FindEmail", ReplyAction="http://tempuri.org/IReservationManagment/FindEmailResponse")]
        System.Threading.Tasks.Task<bool> FindEmailAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservationManagment/FindUser", ReplyAction="http://tempuri.org/IReservationManagment/FindUserResponse")]
        AdminGUI.ReservationService.User FindUser(string login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservationManagment/FindUser", ReplyAction="http://tempuri.org/IReservationManagment/FindUserResponse")]
        System.Threading.Tasks.Task<AdminGUI.ReservationService.User> FindUserAsync(string login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservationManagment/MakeReservation", ReplyAction="http://tempuri.org/IReservationManagment/MakeReservationResponse")]
        int MakeReservation(AdminGUI.ReservationService.Connection con);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservationManagment/MakeReservation", ReplyAction="http://tempuri.org/IReservationManagment/MakeReservationResponse")]
        System.Threading.Tasks.Task<int> MakeReservationAsync(AdminGUI.ReservationService.Connection con);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservationManagment/AddUser", ReplyAction="http://tempuri.org/IReservationManagment/AddUserResponse")]
        void AddUser(AdminGUI.ReservationService.User a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservationManagment/AddUser", ReplyAction="http://tempuri.org/IReservationManagment/AddUserResponse")]
        System.Threading.Tasks.Task AddUserAsync(AdminGUI.ReservationService.User a);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IReservationManagmentChannel : AdminGUI.ReservationService.IReservationManagment, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReservationManagmentClient : System.ServiceModel.ClientBase<AdminGUI.ReservationService.IReservationManagment>, AdminGUI.ReservationService.IReservationManagment {
        
        public ReservationManagmentClient() {
        }
        
        public ReservationManagmentClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReservationManagmentClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReservationManagmentClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReservationManagmentClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AdminGUI.ReservationService.Station[] DepartureStations() {
            return base.Channel.DepartureStations();
        }
        
        public System.Threading.Tasks.Task<AdminGUI.ReservationService.Station[]> DepartureStationsAsync() {
            return base.Channel.DepartureStationsAsync();
        }
        
        public AdminGUI.ReservationService.Station[] ArrivalStations() {
            return base.Channel.ArrivalStations();
        }
        
        public System.Threading.Tasks.Task<AdminGUI.ReservationService.Station[]> ArrivalStationsAsync() {
            return base.Channel.ArrivalStationsAsync();
        }
        
        public AdminGUI.ReservationService.Connection[] FindConnection(AdminGUI.ReservationService.Station departure, AdminGUI.ReservationService.Station arrival, System.DateTime date) {
            return base.Channel.FindConnection(departure, arrival, date);
        }
        
        public System.Threading.Tasks.Task<AdminGUI.ReservationService.Connection[]> FindConnectionAsync(AdminGUI.ReservationService.Station departure, AdminGUI.ReservationService.Station arrival, System.DateTime date) {
            return base.Channel.FindConnectionAsync(departure, arrival, date);
        }
        
        public bool FindEmail(string email) {
            return base.Channel.FindEmail(email);
        }
        
        public System.Threading.Tasks.Task<bool> FindEmailAsync(string email) {
            return base.Channel.FindEmailAsync(email);
        }
        
        public AdminGUI.ReservationService.User FindUser(string login) {
            return base.Channel.FindUser(login);
        }
        
        public System.Threading.Tasks.Task<AdminGUI.ReservationService.User> FindUserAsync(string login) {
            return base.Channel.FindUserAsync(login);
        }
        
        public int MakeReservation(AdminGUI.ReservationService.Connection con) {
            return base.Channel.MakeReservation(con);
        }
        
        public System.Threading.Tasks.Task<int> MakeReservationAsync(AdminGUI.ReservationService.Connection con) {
            return base.Channel.MakeReservationAsync(con);
        }
        
        public void AddUser(AdminGUI.ReservationService.User a) {
            base.Channel.AddUser(a);
        }
        
        public System.Threading.Tasks.Task AddUserAsync(AdminGUI.ReservationService.User a) {
            return base.Channel.AddUserAsync(a);
        }
    }
}
