//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUI.ReservationService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ReservationService.IReservationManagment")]
    public interface IReservationManagment {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservationManagmentUnsecure/AddUser", ReplyAction="http://tempuri.org/IReservationManagmentUnsecure/AddUserResponse")]
        void AddUser(DomainModel.Models.User a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservationManagmentUnsecure/AddUser", ReplyAction="http://tempuri.org/IReservationManagmentUnsecure/AddUserResponse")]
        System.Threading.Tasks.Task AddUserAsync(DomainModel.Models.User a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservationManagmentUnsecure/AllStations", ReplyAction="http://tempuri.org/IReservationManagmentUnsecure/AllStationsResponse")]
        System.Collections.Generic.List<DomainModel.Models.Station> AllStations();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservationManagmentUnsecure/AllStations", ReplyAction="http://tempuri.org/IReservationManagmentUnsecure/AllStationsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<DomainModel.Models.Station>> AllStationsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservationManagmentUnsecure/FindConnection", ReplyAction="http://tempuri.org/IReservationManagmentUnsecure/FindConnectionResponse")]
        System.Collections.Generic.List<DomainModel.Models.Connection> FindConnection(DomainModel.Models.Station departure, DomainModel.Models.Station arrival, System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservationManagmentUnsecure/FindConnection", ReplyAction="http://tempuri.org/IReservationManagmentUnsecure/FindConnectionResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<DomainModel.Models.Connection>> FindConnectionAsync(DomainModel.Models.Station departure, DomainModel.Models.Station arrival, System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservationManagment/MakeReservation", ReplyAction="http://tempuri.org/IReservationManagment/MakeReservationResponse")]
        int MakeReservation(DomainModel.Models.Connection con);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservationManagment/MakeReservation", ReplyAction="http://tempuri.org/IReservationManagment/MakeReservationResponse")]
        System.Threading.Tasks.Task<int> MakeReservationAsync(DomainModel.Models.Connection con);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IReservationManagmentChannel : GUI.ReservationService.IReservationManagment, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReservationManagmentClient : System.ServiceModel.ClientBase<GUI.ReservationService.IReservationManagment>, GUI.ReservationService.IReservationManagment {
        
        public ReservationManagmentClient() {
        }
        
        public ReservationManagmentClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReservationManagmentClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReservationManagmentClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReservationManagmentClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AddUser(DomainModel.Models.User a) {
            base.Channel.AddUser(a);
        }
        
        public System.Threading.Tasks.Task AddUserAsync(DomainModel.Models.User a) {
            return base.Channel.AddUserAsync(a);
        }
        
        public System.Collections.Generic.List<DomainModel.Models.Station> AllStations() {
            return base.Channel.AllStations();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<DomainModel.Models.Station>> AllStationsAsync() {
            return base.Channel.AllStationsAsync();
        }
        
        public System.Collections.Generic.List<DomainModel.Models.Connection> FindConnection(DomainModel.Models.Station departure, DomainModel.Models.Station arrival, System.DateTime date) {
            return base.Channel.FindConnection(departure, arrival, date);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<DomainModel.Models.Connection>> FindConnectionAsync(DomainModel.Models.Station departure, DomainModel.Models.Station arrival, System.DateTime date) {
            return base.Channel.FindConnectionAsync(departure, arrival, date);
        }
        
        public int MakeReservation(DomainModel.Models.Connection con) {
            return base.Channel.MakeReservation(con);
        }
        
        public System.Threading.Tasks.Task<int> MakeReservationAsync(DomainModel.Models.Connection con) {
            return base.Channel.MakeReservationAsync(con);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ReservationService.IReservationManagmentUnsecure")]
    public interface IReservationManagmentUnsecure {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservationManagmentUnsecure/AddUser", ReplyAction="http://tempuri.org/IReservationManagmentUnsecure/AddUserResponse")]
        void AddUser(DomainModel.Models.User a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservationManagmentUnsecure/AddUser", ReplyAction="http://tempuri.org/IReservationManagmentUnsecure/AddUserResponse")]
        System.Threading.Tasks.Task AddUserAsync(DomainModel.Models.User a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservationManagmentUnsecure/AllStations", ReplyAction="http://tempuri.org/IReservationManagmentUnsecure/AllStationsResponse")]
        System.Collections.Generic.List<DomainModel.Models.Station> AllStations();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservationManagmentUnsecure/AllStations", ReplyAction="http://tempuri.org/IReservationManagmentUnsecure/AllStationsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<DomainModel.Models.Station>> AllStationsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservationManagmentUnsecure/FindConnection", ReplyAction="http://tempuri.org/IReservationManagmentUnsecure/FindConnectionResponse")]
        System.Collections.Generic.List<DomainModel.Models.Connection> FindConnection(DomainModel.Models.Station departure, DomainModel.Models.Station arrival, System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservationManagmentUnsecure/FindConnection", ReplyAction="http://tempuri.org/IReservationManagmentUnsecure/FindConnectionResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<DomainModel.Models.Connection>> FindConnectionAsync(DomainModel.Models.Station departure, DomainModel.Models.Station arrival, System.DateTime date);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IReservationManagmentUnsecureChannel : GUI.ReservationService.IReservationManagmentUnsecure, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReservationManagmentUnsecureClient : System.ServiceModel.ClientBase<GUI.ReservationService.IReservationManagmentUnsecure>, GUI.ReservationService.IReservationManagmentUnsecure {
        
        public ReservationManagmentUnsecureClient() {
        }
        
        public ReservationManagmentUnsecureClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReservationManagmentUnsecureClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReservationManagmentUnsecureClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReservationManagmentUnsecureClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AddUser(DomainModel.Models.User a) {
            base.Channel.AddUser(a);
        }
        
        public System.Threading.Tasks.Task AddUserAsync(DomainModel.Models.User a) {
            return base.Channel.AddUserAsync(a);
        }
        
        public System.Collections.Generic.List<DomainModel.Models.Station> AllStations() {
            return base.Channel.AllStations();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<DomainModel.Models.Station>> AllStationsAsync() {
            return base.Channel.AllStationsAsync();
        }
        
        public System.Collections.Generic.List<DomainModel.Models.Connection> FindConnection(DomainModel.Models.Station departure, DomainModel.Models.Station arrival, System.DateTime date) {
            return base.Channel.FindConnection(departure, arrival, date);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<DomainModel.Models.Connection>> FindConnectionAsync(DomainModel.Models.Station departure, DomainModel.Models.Station arrival, System.DateTime date) {
            return base.Channel.FindConnectionAsync(departure, arrival, date);
        }
    }
}
